# Generated by Django 3.1.7 on 2021-03-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_auto_20210330_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="files",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
    ]
