# Generated by Django 3.1.2 on 2021-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_auto_20210330_2035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="Post/%Y/%m/%d/"),
        ),
    ]
