# Generated by Django 3.1.2 on 2021-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="noname", max_length=10),
        ),
    ]
